### ISSUE TITLE
Wrong constructor usage when trying to set and object with a script attach in editor.

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin-jvm#118]
I created a custom kotlin class, `Species`, inheriting from `Resource`: 
![image](https://user-images.githubusercontent.com/48322356/112879316-44153980-90c9-11eb-82f2-1e171ed4b49e.png)
Then, I have a `Monster` class inheriting `Object` which has a `Species` registered.  
When I set a registered `.tres` species in a `Monster` and then start scene, I got this cast error:  
```
Exception in thread "main" java.lang.ClassCastException: class godot.Resource cannot be cast to class com.utopiarise.evolia.client.battleproto.monster.Species (godot.Resource is in unnamed module of loader java.net.URLClassLoader @619a5dff; com.utopiarise.evolia.client.battleproto.monster.Species is in unnamed module of loader java.net.URLClassLoader @6adca536)
        at godot.com.utopiarise.evolia.client.battleproto.monster.MonsterRegistrar$register$1$1$2.set(MonsterEntry.kt:20)
        at godot.core.KtProperty.callSet(Properties.kt:37)
```

We should be able to create jvm user instances from cpp, but currently, that's a case we do not cover.  
To make this happens, we need to make use of user constructors [here](https://github.com/utopia-rise/godot-kotlin-jvm/blob/e7b529d823309a7ea810d2a9acc1ed03512eec4e/kt/godot-runtime/src/main/kotlin/godot/core/Variant.kt#L305) when needed.  
This also needs to add sending of user constructor index in [KtVariant::to_kvariant_fromOBJECT](https://github.com/utopia-rise/godot-kotlin-jvm/blob/e7b529d823309a7ea810d2a9acc1ed03512eec4e/src/kt_variant.h#L227).

**Comment by piiertho** [comment]
Maybe we have a deeper problem, here is full log:
```
Godot-JVM: Try to create res://src/main/kotlin/com/utopiarise/evolia/client/battleproto/monster/Species.kt instance.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 1191 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.set(ArrayList.java:473)
        at godot.core.GarbageCollector.registerReference(GarbageCollector.kt:95)
        at godot.core.KtObject.<init>(KtObject.kt:59)
        at godot.Object.<init>(Object.kt:79)
        at godot.Reference.<init>(Reference.kt:27)
        at com.utopiarise.evolia.client.battleproto.monster.Species.<init>(Species.kt:9)
        at godot.com.utopiarise.evolia.client.battleproto.monster.SpeciesRegistrar$register$1$1$1.invoke(SpeciesEntry.kt:30)
        at godot.com.utopiarise.evolia.client.battleproto.monster.SpeciesRegistrar$register$1$1$1.invoke(SpeciesEntry.kt:14)
        at godot.core.KtConstructor0.invoke(Constructors.kt:47)
        at godot.core.KtConstructor$construct$1.invoke(Constructors.kt:29)
        at godot.core.KtConstructor$construct$1.invoke(Constructors.kt:11)
        at godot.core.KtObject$Companion.instantiateWith(KtObject.kt:88)
        at godot.core.KtConstructor.construct(Constructors.kt:20)
ERROR: Godot-JVM: An exception has occurred!
   At: modules\kotlin_jvm\src\jni\env.cpp:61
WARNING: JNI local refs: 66, exceeds capacity: 65
Godot-JVM: Instantiated an object of type res://src/main/kotlin/com/utopiarise/evolia/client/battleproto/monster/Species.kt
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method godot.core.KtProperty.callSet, parameter instance
        at godot.core.KtProperty.callSet(Properties.kt)
ERROR: Godot-JVM: An exception has occurred!
   At: modules\kotlin_jvm\src\jni\env.cpp:61
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method godot.core.KtProperty.callSet, parameter instance
        at godot.core.KtProperty.callSet(Properties.kt)
ERROR: Godot-JVM: An exception has occurred!
   At: modules\kotlin_jvm\src\jni\env.cpp:61
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method godot.core.KtProperty.callSet, parameter instance
        at godot.core.KtProperty.callSet(Properties.kt)
ERROR: Godot-JVM: An exception has occurred!
   At: modules\kotlin_jvm\src\jni\env.cpp:61
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method godot.core.KtProperty.callSet, parameter instance
        at godot.core.KtProperty.callSet(Properties.kt)
ERROR: Godot-JVM: An exception has occurred!
   At: modules\kotlin_jvm\src\jni\env.cpp:61
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method godot.core.KtProperty.callSet, parameter instance
        at godot.core.KtProperty.callSet(Properties.kt)
ERROR: Godot-JVM: An exception has occurred!
   At: modules\kotlin_jvm\src\jni\env.cpp:61
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method godot.core.KtProperty.callSet, parameter instance
        at godot.core.KtProperty.callSet(Properties.kt)
ERROR: Godot-JVM: An exception has occurred!
   At: modules\kotlin_jvm\src\jni\env.cpp:61
Godot-JVM: Try to create res://src/main/kotlin/com/utopiarise/evolia/client/battleproto/monster/Monster.kt instance.
Godot-JVM: Instantiated an object of type res://src/main/kotlin/com/utopiarise/evolia/client/battleproto/monster/Monster.kt
Exception in thread "main" java.lang.ClassCastException: class godot.Resource cannot be cast to class com.utopiarise.evolia.client.battleproto.monster.Species (godot.Resource is in unnamed module of loader java.net.URLClassLoader @619a5dff; com.utopiarise.evolia.client.battleproto.monster.Species is in unnamed module of loader java.net.URLClassLoader @6adca536)
        at godot.com.utopiarise.evolia.client.battleproto.monster.MonsterRegistrar$register$1$1$2.set(MonsterEntry.kt:20)
        at godot.core.KtProperty.callSet(Properties.kt:37)
ERROR: Godot-JVM: An exception has occurred!
   At: modules\kotlin_jvm\src\jni\env.cpp:61
```

It seems we have a problem while registering in GC.
