### ISSUE TITLE
WARNING: JNI local refs: 66, exceeds capacity: 65

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#233]
I have those warning since the beginning. How can I check what is wrong?

```
WARNING: JNI local refs: 33, exceeds capacity: 32
Godot-JVM: Starting GC thread
WARNING: JNI local refs: 66, exceeds capacity: 65
Godot-JVM: Loading classes ...
WARNING: JNI local refs: 33, exceeds capacity: 32
	at godot.runtime.Bootstrap.loadClasses(Native Method)
	at godot.runtime.Bootstrap.doInit(Bootstrap.kt:114)
	at godot.runtime.Bootstrap.init(Bootstrap.kt:34)
WARNING: JNI local refs: 66, exceeds capacity: 65
	at godot.runtime.Bootstrap.registerUserTypesMembers(Native Method)
	at godot.runtime.Bootstrap.doInit(Bootstrap.kt:116)
	at godot.runtime.Bootstrap.init(Bootstrap.kt:34)
WARNING: JNI local refs: 99, exceeds capacity: 98
	at godot.runtime.Bootstrap.registerUserTypesMembers(Native Method)
	at godot.runtime.Bootstrap.doInit(Bootstrap.kt:116)
	at godot.runtime.Bootstrap.init(Bootstrap.kt:34)
WARNING: JNI local refs: 132, exceeds capacity: 131
	at godot.runtime.Bootstrap.registerUserTypesMembers(Native Method)
	at godot.runtime.Bootstrap.doInit(Bootstrap.kt:116)
	at godot.runtime.Bootstrap.init(Bootstrap.kt:34)
WARNING: JNI local refs: 165, exceeds capacity: 164
	at godot.runtime.Bootstrap.registerUserTypesMembers(Native Method)
	at godot.runtime.Bootstrap.doInit(Bootstrap.kt:116)
	at godot.runtime.Bootstrap.init(Bootstrap.kt:34)
WARNING: JNI local refs: 198, exceeds capacity: 197
	at godot.runtime.Bootstrap.registerUserTypesMembers(Native Method)
	at godot.runtime.Bootstrap.doInit(Bootstrap.kt:116)
	at godot.runtime.Bootstrap.init(Bootstrap.kt:34)
WARNING: JNI local refs: 231, exceeds capacity: 230
	at godot.runtime.Bootstrap.registerUserTypesMembers(Native Method)
	at godot.runtime.Bootstrap.doInit(Bootstrap.kt:116)
	at godot.runtime.Bootstrap.init(Bootstrap.kt:34)
```

**Comment by CedNaru** [comment]
It's just that we forgot to release some JNI variables in the C++ code. We know the source of it, you don't need to investigate, it's going to be fixed when we give it a bit of time.

**Comment by CedNaru** [comment]
Closing this issue, the warning often disappear and reappear as a fix leaking local refs and introduce new ones every X patches. Up to me to be cautious about no adding them back for each PR.
