### ISSUE TITLE
bootstrap.jar can't read white spaces on a file path

### ISSUE THREAD

**Issue by asprootone** [utopia-rise/godot-kotlin-jvm#353]
If you use white spaces or symbols (i.e. '#,$,&,*'), bootstrap.jar seems to not be able to read the filepath and throws some random error such as this :
```
Exception in thread "main" java.lang.ClassNotFoundException: godot.core.TransferContext
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
ERROR: Godot-JVM: An exception has occurred!
   at: (modules\kotlin_jvm\src\jni\env.cpp:67)
FATAL ERROR in native method: Bad global or local ref passed to JNI

```

**Comment by piiertho** [comment]
Is this windows only ?
